<?php
class ELRHPageContentRenderer {
	public static function renderContent($page_data) {
		// use "echo" function to render all contents of current page
		echo '<h1>Bc. ALOIS SEČKÁR</h1>'.PHP_EOL;
		echo '<p>'.PHP_EOL;
			echo '<a href="web/content/CV.pdf" title="CV.pdf">Životopis v PDF</a>'.PHP_EOL;
		echo '</p>'.PHP_EOL;
		echo '<ul>'.PHP_EOL;
			echo '<li>21. 07. 1988</li>'.PHP_EOL;
			echo '<li>Matek 5, 14000 Praha 4</li>'.PHP_EOL;
			echo '<li>+420 721 302 700</li>'.PHP_EOL;
			echo '<li>seckar@svobodni.cz</li>'.PHP_EOL;
			echo '<li>http://alois-seckar.cz</li>'.PHP_EOL;
		echo '</ul>'.PHP_EOL;
		 echo '<h2>VZDĚLÁNÍ</h2>'.PHP_EOL;
        echo '<ul>'.PHP_EOL;
			echo '<li><strong>2010 – 2013</strong> - Vysoká Škola Ekonomická v&nbsp;Praze, FIS, Praha, Bc.,&nbsp;obor Aplikovaná Informatika</li>'.PHP_EOL;
			echo '<li><strong>2003 – 2007</strong> - Gymnázium Na&nbsp;Vítězné pláni, Praha, Všeobecné čtyřleté gymnázium</li>'.PHP_EOL;
			echo '<li><strong>1996 – 2003</strong> - 1.&nbsp;JZŠ Horáčkova, Praha, Výběrová škola s&nbsp;rozšířenou výukou jazyků (3. – 9. třída)</li>'.PHP_EOL;
		echo '</ul>'.PHP_EOL;
		echo '<p>'.PHP_EOL;
			echo 'V&nbsp;současné době <strong>(2013 – 2016)</strong> navazující magisterské studium na FIS VŠE v Praze, obor Informační systémy a&nbsp;technologie.'.PHP_EOL;
		echo '</p>'.PHP_EOL;
		echo '<p>'.PHP_EOL;
			echo 'V letech 2007 – 2010 neukončené bakalářské studium na MFF UK v&nbsp;Praze, obor Informatika.'.PHP_EOL;
		echo '</p>'.PHP_EOL;
		echo '<h2>ZAMĚSTNÁNÍ</h2>'.PHP_EOL;
        echo '<ul>'.PHP_EOL;
			echo '<li><strong>07/2014 – 12/2015</strong> - Petr Mach - Europoslanec; Asistent - administrativní práce v&nbsp;europoslanecké kanceláři v&nbsp;Praze.</li>'.PHP_EOL;
			echo '<li><strong>03/2014 – 11/2015</strong> - Strana svobodných občanů; Pracovník Republikové kanceláře - vedení zápisů ze schůzí, správa uživatelů, vyřizování dotazů, administrativní podpora vedení strany.</li>'.PHP_EOL;
		echo '</ul>'.PHP_EOL;
		echo '<h3>PŘÍLEŽITOSTNĚ</h3>'.PHP_EOL;
        echo '<ul>'.PHP_EOL;
			echo '<li><strong>2012 – souč.</strong> - Česká Baseballová Asociace; Zapisovatel - organizace a&nbsp;technická podpora zapisovatelského systému, zajištění mezinár. turnajů, práce se software TASBS, rozvoj zápisu v&nbsp;ČR.</li>'.PHP_EOL;
			echo '<li><strong>2009 – souč.</strong> - Česká Sofbtallová Asociace; Zapisovatel - organizace a&nbsp;technická podpora zapisovatelského systému, zajištění mezinár. turnajů, práce se software TASBS a&nbsp;iScore, rozvoj zápisu v&nbsp;ČR.</li>'.PHP_EOL;
		echo '</ul>'.PHP_EOL;
		echo '<h2>JAZYKOVÉ ZNALOSTI</h2>'.PHP_EOL;
        echo '<ul>'.PHP_EOL;
			echo '<li>Anglický jazyk – aktivní</li>'.PHP_EOL;
			echo '<li>Německý jazyk – středně pokročilý</li>'.PHP_EOL;
			echo '<li>Španělský jazyk – začátečník/mírně pokročilý</li>'.PHP_EOL;
		echo '</ul>'.PHP_EOL;
		echo '<h2>IT ZNALOSTI</h2>'.PHP_EOL;
        echo '<ul>'.PHP_EOL;
			echo '<li>Internet (e-mail, služby, orientace v síti) – expert</li>'.PHP_EOL;
			echo '<li>Sociální sítě – pokročilý</li>'.PHP_EOL;
			echo '<li>Microsoft Office/Open Office – pokročilý, skvělá znalost běžné uživatelské práce</li>'.PHP_EOL;
			echo '<li>HTML, PHP – expert</li>'.PHP_EOL;
			echo '<li>CSS, JavaScript – mírně pokročilý</li>'.PHP_EOL;
			echo '<li>MySQL, Oracle DB – pokročilý</li>'.PHP_EOL;
			echo '<li>Java – pokročilý</li>'.PHP_EOL;
			echo '<li>Delphi, C# - mírně pokročilý</li>'.PHP_EOL;
		echo '</ul>'.PHP_EOL;
		echo '<p>'.PHP_EOL;
			echo 'Obecně velmi dobrá znalost práce s&nbsp;PC, schopnost rychle se zorientovat a&nbsp;naučit se pracovat s&nbsp;novým software. Kvalitní programátorské základy – znalost OOP, schopnost práce s&nbsp;databázemi, povědomí o&nbsp;známých algoritmech a&nbsp;programovacích technikách, schopnost rychle zvládnout nový programovací jazyk.'.PHP_EOL;
		echo '</p>'.PHP_EOL;
		echo '<h2>VLASTNOSTI</h2>'.PHP_EOL;
		echo '<p>'.PHP_EOL;
			echo 'Spolehlivost, pečlivost, ochota učit se novým věcem, analytické a&nbsp;kritické myšlení, kvalitní úroveň psaného projevu, zájem o&nbsp;aktuální dění a&nbsp;souvislosti.'.PHP_EOL;
		echo '</p>'.PHP_EOL;
		echo '<h2>ZÁJMY</h2>'.PHP_EOL;
        echo '<ul>'.PHP_EOL;
			echo '<li><strong>Sport</strong> - Aktivně softbal, malý fotbal (brankář), běh, dříve veslování, florbal, taekwon-do, pasivně zájem o&nbsp;široké spektrum sportů. Aktivní rozhodčí baseballu a&nbsp;softbalu.</li>'.PHP_EOL;
			echo '<li><strong>Politika</strong> - Aktivní člen politické strany Svobodných, koordinátor místní pobočky Praha 4; platforma pro prezentaci osobních názorů - zde na webu</li>'.PHP_EOL;
			echo '<li><strong>Tvorba webu</strong> - Výběr z projektů například www.metin2encyklopedie.cz a&nbsp;www.krc-historie.cz (další ukázky zde na webu)</li>'.PHP_EOL;
			echo '<li><strong>Literatura</strong> - Historie, beletrie (sci-fi a&nbsp;fantasy), vč. vlastní tvorby – povídky +&nbsp;hudební recenze (seznam publikovaných prací zde na webu)</li>'.PHP_EOL;
			echo '<li><strong>Hudba</strong> - Především rock a&nbsp;metal, nebráním se ovšem kvalitní tvorbě z&nbsp;žádného žánru. Existují pokusy o&nbsp;vlastní tvorbu (více zde na webu)</li>'.PHP_EOL;
			echo '<li><strong>Fotografie</strong> - Příležitostné amatérské focení většinou přírodních motivů (ukázky zde na webu)</li>'.PHP_EOL;
		echo '</ul>'.PHP_EOL;
		echo '<p>'.PHP_EOL;
			echo '<em>Aktualizováno: 6. prosince 2015</em>'.PHP_EOL;
		echo '</p>'.PHP_EOL;
	}
}